### ISSUE TITLE
Windows启动报错

### ISSUE THREAD

**Issue by cweijan** [lwch/natpass#10]
看起来是说文件通配符识别不了.
![image](https://user-images.githubusercontent.com/27798227/141718397-b34177ed-56dc-4af3-a66e-3f9bf0c00b25.png)

**Comment by hackzx** [comment]
遇到了同样的问题，如何解决的？

**Comment by lwch** [comment]
> 遇到了同样的问题，如何解决的？

这个问题的原因已找到，这两天会发布v0.7.2版本将会修复这个问题

**Comment by lwch** [comment]
> 遇到了同样的问题，如何解决的？

这个问题的原因已找到，这两天会发布v0.7.2版本将会修复这个问题，目前临时的解决方案是修改配置文件中的include语句，将其中含有*.yaml的配置项修改为具体的文件名，如

    将配置文件中的#include conf.d/*.yaml修改为
    #include conf.d/conn.yaml
    #include conf.d/log.yaml
