### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by houzy** [lwch/natpass#30]
能否添加远程打开设备web界面的功能
理由：
很多边端设备是嵌入式设备，没有桌面环境，但是提供了web访问界面

**Comment by lwch** [comment]
您好，可通过配置文件中的dashboard下的enabled配置项来控制是否开启web页面

![image](https://user-images.githubusercontent.com/4181963/167348770-47ed9880-a64e-42a1-8432-0f7073cdd9cb.png)

**Comment by houzy** [comment]
感谢回复。您的意思是当前项目已经具备了打开远端设备web界面的功能？我看介绍中有打开shell和vnc的功能，没有打开web界面的介绍？

**Comment by lwch** [comment]
所有规则均为正向配置，既我要访问比如win2008这台机器的远程桌面，也在我当前服务的配置文件中配置到win2008的规则即可，因此你这边的需求只要不配置对应的规则就可关闭相应的功能了。不知道我的理解有没有问题？

**Comment by houzy** [comment]
也就是说我仿照远程桌面或者终端的规则，配置一个访问设备web界面的规则，比如80端口这样一条规则，就可以访问到设备的web界面了，是这个意思吧？

**Comment by lwch** [comment]
是的natpass的设计初衷是为了远程访问设备用的，因此两端都必须安装client中间通过server进行转发

**Comment by houzy** [comment]
嗯，这个明白，有时间我试试，多谢
