### ISSUE TITLE
目标鼠标位置不对

### ISSUE THREAD

**Issue by 0x457** [lwch/natpass#34]
mac - control- window
控制时，鼠标位置不对，左右差很多，可能我mac用外挂显示器吗？

**Comment by lwch** [comment]
您好，能否提供macos版本号和屏幕分辨率等信息

**Comment by 0x457** [comment]
对了，还有window状态栏在vnc页面上，也看不见。

**Comment by 0x457** [comment]
window端是1920*1080，且缩放125%

**Comment by lwch** [comment]
v0.12.2 版本已修复
