### ISSUE TITLE
Got some error stright after deployment

### ISSUE THREAD

**Issue by TAI-REx** [lwch/natpass#36]
~/natpass_0.9.0                                                                                                                        
❯ bat server.yaml          
──────────────
   1   │ listen: 6154 # 监听端口号
   2   │ #include common.yaml
   3   │ #tls:
   4   │ #  key: /dir/to/tls/key/file # tls密钥
   5   │ #  crt: /dir/to/tls/crt/file # tls证书

Below log of errors which was occurred after I tried to  open -> http://vpsip:6541 if i do http://vpsip:8080 - I cant connect ether 

 ubuntuvnc 19:36    ~/natpass_0.9.0                                                                                                                                   
❯ ./np-svr -conf server.yaml
2022/07/11 20:09:38 [ERROR]read handshake from 45.15.16.60:51496 1 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51496: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:38 [ERROR]read handshake from 45.15.16.60:51492 1 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51492: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 2 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 3 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 4 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 5 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 6 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 7 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 8 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 9 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:39 [ERROR]read handshake from 45.15.16.60:51496 10 times, err=EOF
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:43 [ERROR]read handshake from 45.15.16.60:51492 2 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51492: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:48 [ERROR]read handshake from 45.15.16.60:51492 3 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51492: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:53 [ERROR]read handshake from 45.15.16.60:51492 4 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51492: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:09:58 [ERROR]read handshake from 45.15.16.60:51492 5 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51492: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle
2022/07/11 20:10:03 [ERROR]read handshake from 45.15.16.60:51492 6 times, err=read tcp 185.102.170.197:6154->45.15.16.60:51492: i/o timeout
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20220322084100-ec48185d95ab/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:67) github.com/lwch/natpass/code/server/handler.(*Handler).Handle

Server environments : Linux version 5.4.0-29-generic (buildd@lgw01-amd64-035) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020

**Comment by lwch** [comment]
It looks like the server can not received handshake packet, if client and server have the large lag, can you change more timeout seconds from common.yaml and try again?
