### ISSUE TITLE
2022/11/27 15:53:22 [ERROR]invalid handshake from 172.16.17.136:50278   + (/github/home/go/pkg/mod/github.com/lwch/logging@v0.0.0-20221013035348-e250895ebb72/log.go:30) github.com/lwch/logging.Error   + (/github/workspace/code/server/handler/handler.go:64) github.com/lwch/natpass/code/server/handler.(*Handler).Handle

### ISSUE THREAD

**Issue by chaiwanliang** [lwch/natpass#59]
2022/11/27 15:53:22 [ERROR]invalid handshake from 172.16.17.136:50278
  + (/github/home/go/pkg/mod/github.com/lwch/logging@v0.0.0-20221013035348-e250895ebb72/log.go:30) github.com/lwch/logging.Error
  + (/github/workspace/code/server/handler/handler.go:64) github.com/lwch/natpass/code/server/handler.(*Handler).Handle

**Comment by lwch** [comment]
你好，请检查客户端与服务器端所在机器的时间是否一致

**Comment by chaiwanliang** [comment]
你好，之前确实不一致，改回来还会报同样的问题

**Comment by lwch** [comment]
在握手过程中会用到当前时间戳与common.yaml配置文件中的secret，如果这两个参数不一致的话会出现握手失败的情况

**Comment by chaiwanliang** [comment]
已解决

**Comment by SkewwG** [comment]
控制端出现上述的报错内容，控制端和服务端的时间一致，common.yaml配置文件的secret的值也一致
报错内容
<img width="759" alt="image" src="https://user-images.githubusercontent.com/28807688/210041741-225ef76e-45dc-4bbe-8466-59311b649fb8.png">

控制端的时间
<img width="78" alt="image" src="https://user-images.githubusercontent.com/28807688/210041621-bd026bc5-2751-4ee1-b101-70c601941d4c.png">
服务端的时间
<img width="218" alt="image" src="https://user-images.githubusercontent.com/28807688/210041633-75030585-9d23-4d77-bba8-2fd1ce29cc8b.png">
服务端的common.yaml
<img width="537" alt="image" src="https://user-images.githubusercontent.com/28807688/210041652-77c2b486-f675-4e1f-8e20-8ad3256fc1e9.png">
控制端的common.yaml
<img width="697" alt="image" src="https://user-images.githubusercontent.com/28807688/210041668-29984153-9d9a-4458-a186-ee0912ed22a1.png">
