### ISSUE TITLE
[ERROR]invalid handshake from X.X.X.X:XXXXX   + (/github/home/go/pkg/mod/github.com/lwch/logging@v0.0.0-20221013035348-e250895ebb72/log.go:30) github.com/lwch/logging.Error   + (/github/workspace/code/server/handler/handler.go:64) github.com/lwch/natpass/code/server/handler.(*Handler).Handle

### ISSUE THREAD

**Issue by SkewwG** [lwch/natpass#62]
控制端出现上述的报错内容，控制端和服务端的时间一致，common.yaml配置文件的secret的值也一致
报错内容
<img width="759" alt="image" src="https://user-images.githubusercontent.com/28807688/210041741-225ef76e-45dc-4bbe-8466-59311b649fb8.png">

控制端的时间
<img width="78" alt="image" src="https://user-images.githubusercontent.com/28807688/210041621-bd026bc5-2751-4ee1-b101-70c601941d4c.png">
服务端的时间
<img width="218" alt="image" src="https://user-images.githubusercontent.com/28807688/210041633-75030585-9d23-4d77-bba8-2fd1ce29cc8b.png">
服务端的common.yaml
<img width="537" alt="image" src="https://user-images.githubusercontent.com/28807688/210041652-77c2b486-f675-4e1f-8e20-8ad3256fc1e9.png">
控制端的common.yaml
<img width="697" alt="image" src="https://user-images.githubusercontent.com/28807688/210041668-29984153-9d9a-4458-a186-ee0912ed22a1.png">

_Originally posted by @SkewwG in https://github.com/lwch/natpass/issues/59#issuecomment-1367751979_

**Comment by lwch** [comment]
你好请检查时区是否一致，服务端的时区是UTC时间，客户端的时区图上看不出来

**Comment by SkewwG** [comment]
感谢，解决问题了
