### ISSUE TITLE
请教一下,window下开启服务端,报这个错

### ISSUE THREAD

**Issue by zc627788** [lwch/natpass#80]
![image](https://github.com/lwch/natpass/assets/52641919/df5d0b2b-857d-4ea4-bd67-ab0464f66455)

**Comment by zc627788** [comment]
我也试过, start np-sve.exe -conf server.yaml,有个对话框闪了下就消失了

**Comment by lwch** [comment]
cobra这个库要求的传参方式是两个减号，也就是--conf

**Comment by zc627788** [comment]
感谢,ok了
